#
# Crowdin CLI configuration for Documentation translations
# See https://crowdin.github.io/crowdin-cli/configuration for more information
#

"project_id": 2
"preserve_hierarchy": true
"base_url": "https://clientvault.api.crowdin.com"
"base_path": ".."

files: [
  {
    #
    # MDX documentation files - user-guide
    # Using md type to preserve JSX component structure
    # This prevents Crowdin from reformatting <Warning>, <Accordion>, etc.
    #
    "source": "packages/clientvault-docs/user-guide/**/*.mdx",
    "translation": "packages/clientvault-docs/l/%two_letters_code%/user-guide/**/%original_file_name%",
  },
  {
    #
    # MDX documentation files - developers
    # Using md type to preserve JSX component structure
    #
    "source": "packages/clientvault-docs/developers/**/*.mdx",
    "translation": "packages/clientvault-docs/l/%two_letters_code%/developers/**/%original_file_name%",
  },
  {
    #
    # MDX documentation files - clientvault-ui
    # Using md type to preserve JSX component structure
    #
    "source": "packages/clientvault-docs/clientvault-ui/**/*.mdx",
    "translation": "packages/clientvault-docs/l/%two_letters_code%/clientvault-ui/**/%original_file_name%",
  },
  {
    #
    # Navigation labels template - translated into per-locale navigation.json
    #
    "source": "packages/clientvault-docs/navigation/navigation.template.json",
    "translation": "packages/clientvault-docs/l/%two_letters_code%/navigation.json",
  }
]

