#
# Crowdin CLI configuration for App translations (clientvault-front, clientvault-server, clientvault-emails)
# Project ID: 1
# See https://crowdin.github.io/crowdin-cli/configuration for more information
#

"preserve_hierarchy": true
"base_path": ".."

files: [
  {
    #
    # Source files filter - PO files for Lingui
    #
    "source": "**/en.po",

    #
    # Translation files path
    #
    "translation": "%original_path%/%locale%.po",
  }
]

