import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'clientvault-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/clientvault-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/clientvault-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/clientvault-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';
import { getTsVectorColumnExpressionFromFields } from 'src/engine/workspace-manager/utils/get-ts-vector-column-expression.util';
import { SEARCH_FIELDS_FOR_MESSAGE_CHANNEL_MESSAGE_ASSOCIATION } from 'src/modules/messaging/common/standard-objects/message-channel-message-association.workspace-entity';
import { MessageDirection } from 'src/modules/messaging/common/enums/message-direction.enum';

export const buildMessageChannelMessageAssociationStandardFlatFieldMetadatas =
  ({
    now,
    objectName,
    workspaceId,
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    clientvaultStandardApplicationId,
  }: Omit<
    CreateStandardFieldArgs<
      'messageChannelMessageAssociation',
      FieldMetadataType
    >,
    'context'
  >): Record<
    AllStandardObjectFieldName<'messageChannelMessageAssociation'>,
    FlatFieldMetadata
  > => ({
    id: createStandardFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        fieldName: 'id',
        type: FieldMetadataType.UUID,
        label: 'Id',
        description: 'Id',
        icon: 'Icon123',
        isSystem: true,
        isNullable: false,
        isUIReadOnly: true,
        defaultValue: 'uuid',
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      clientvaultStandardApplicationId,
      now,
    }),
    createdAt: createStandardFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        fieldName: 'createdAt',
        type: FieldMetadataType.DATE_TIME,
        label: 'Creation date',
        description: 'Creation date',
        icon: 'IconCalendar',
        isSystem: true,
        isNullable: false,
        isUIReadOnly: true,
        defaultValue: 'now',
        settings: { displayFormat: DateDisplayFormat.RELATIVE },
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      clientvaultStandardApplicationId,
      now,
    }),
    updatedAt: createStandardFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        fieldName: 'updatedAt',
        type: FieldMetadataType.DATE_TIME,
        label: 'Last update',
        description: 'Last time the record was changed',
        icon: 'IconCalendarClock',
        isSystem: true,
        isNullable: false,
        isUIReadOnly: true,
        defaultValue: 'now',
        settings: { displayFormat: DateDisplayFormat.RELATIVE },
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      clientvaultStandardApplicationId,
      now,
    }),
    deletedAt: createStandardFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        fieldName: 'deletedAt',
        type: FieldMetadataType.DATE_TIME,
        label: 'Deleted at',
        description: 'Date when the record was deleted',
        icon: 'IconCalendarMinus',
        isSystem: true,
        isNullable: true,
        isUIReadOnly: true,
        settings: { displayFormat: DateDisplayFormat.RELATIVE },
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      clientvaultStandardApplicationId,
      now,
    }),
    createdBy: createStandardFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        fieldName: 'createdBy',
        type: FieldMetadataType.ACTOR,
        label: 'Created by',
        description: 'The creator of the record',
        icon: 'IconCreativeCommonsSa',
        isSystem: true,
        isUIReadOnly: true,
        isNullable: false,
        defaultValue: {
          source: "'MANUAL'",
          name: "'System'",
          workspaceMemberId: null,
        },
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      clientvaultStandardApplicationId,
      now,
    }),
    updatedBy: createStandardFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        fieldName: 'updatedBy',
        type: FieldMetadataType.ACTOR,
        label: 'Updated by',
        description: 'The workspace member who last updated the record',
        icon: 'IconUserCircle',
        isSystem: true,
        isUIReadOnly: true,
        isNullable: false,
        defaultValue: {
          source: "'MANUAL'",
          name: "'System'",
          workspaceMemberId: null,
        },
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      clientvaultStandardApplicationId,
      now,
    }),
    position: createStandardFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        fieldName: 'position',
        type: FieldMetadataType.POSITION,
        label: 'Position',
        description: 'Message channel message association record position',
        icon: 'IconHierarchy2',
        isSystem: true,
        isNullable: false,
        defaultValue: 0,
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      clientvaultStandardApplicationId,
      now,
    }),
    searchVector: createStandardFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        fieldName: 'searchVector',
        type: FieldMetadataType.TS_VECTOR,
        label: 'Search vector',
        description: 'Field used for full-text search',
        icon: 'IconUser',
        isSystem: true,
        isNullable: true,
        settings: {
          generatedType: 'STORED',
          asExpression: getTsVectorColumnExpressionFromFields(
            SEARCH_FIELDS_FOR_MESSAGE_CHANNEL_MESSAGE_ASSOCIATION,
          ),
        },
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      clientvaultStandardApplicationId,
      now,
    }),
    messageExternalId: createStandardFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        fieldName: 'messageExternalId',
        type: FieldMetadataType.TEXT,
        label: 'Message External Id',
        description: 'Message id from the messaging provider',
        icon: 'IconHash',
        isNullable: true,
        isUIReadOnly: true,
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      clientvaultStandardApplicationId,
      now,
    }),
    messageThreadExternalId: createStandardFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        fieldName: 'messageThreadExternalId',
        type: FieldMetadataType.TEXT,
        label: 'Thread External Id',
        description: 'Thread id from the messaging provider',
        icon: 'IconHash',
        isNullable: true,
        isUIReadOnly: true,
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      clientvaultStandardApplicationId,
      now,
    }),
    direction: createStandardFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        fieldName: 'direction',
        type: FieldMetadataType.SELECT,
        label: 'Direction',
        description: 'Message Direction',
        icon: 'IconDirection',
        isNullable: false,
        isUIReadOnly: true,
        defaultValue: `'${MessageDirection.INCOMING}'`,
        options: [
          {
            value: MessageDirection.INCOMING,
            label: 'Incoming',
            position: 0,
            color: 'green',
          },
          {
            value: MessageDirection.OUTGOING,
            label: 'Outgoing',
            position: 1,
            color: 'blue',
          },
        ],
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      clientvaultStandardApplicationId,
      now,
    }),
    messageChannel: createStandardRelationFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        type: FieldMetadataType.RELATION,
        morphId: null,
        fieldName: 'messageChannel',
        label: 'Message Channel Id',
        description: 'Message Channel Id',
        icon: 'IconHash',
        isNullable: true,
        isUIReadOnly: true,
        targetObjectName: 'messageChannel',
        targetFieldName: 'messageChannelMessageAssociations',
        settings: {
          relationType: RelationType.MANY_TO_ONE,
          onDelete: RelationOnDeleteAction.CASCADE,
          joinColumnName: 'messageChannelId',
        },
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      clientvaultStandardApplicationId,
      now,
    }),
    messageThread: createStandardRelationFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        type: FieldMetadataType.RELATION,
        morphId: null,
        fieldName: 'messageThread',
        label: 'Message Thread Id',
        description: 'Message Thread Id',
        icon: 'IconHash',
        isNullable: true,
        isUIReadOnly: true,
        targetObjectName: 'messageThread',
        targetFieldName: 'messageChannelMessageAssociations',
        settings: {
          relationType: RelationType.MANY_TO_ONE,
          onDelete: RelationOnDeleteAction.CASCADE,
          joinColumnName: 'messageThreadId',
        },
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      clientvaultStandardApplicationId,
      now,
    }),
    message: createStandardRelationFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        type: FieldMetadataType.RELATION,
        morphId: null,
        fieldName: 'message',
        label: 'Message Id',
        description: 'Message Id',
        icon: 'IconHash',
        isNullable: true,
        isUIReadOnly: true,
        targetObjectName: 'message',
        targetFieldName: 'messageChannelMessageAssociations',
        settings: {
          relationType: RelationType.MANY_TO_ONE,
          onDelete: RelationOnDeleteAction.CASCADE,
          joinColumnName: 'messageId',
        },
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      clientvaultStandardApplicationId,
      now,
    }),
    messageFolders: createStandardRelationFieldFlatMetadata({
      objectName,
      workspaceId,
      context: {
        type: FieldMetadataType.RELATION,
        morphId: null,
        fieldName: 'messageFolders',
        label: 'Message Folders',
        description: 'Message Folders (supports multiple folders/labels)',
        icon: 'IconFolders',
        isNullable: true,
        isUIReadOnly: true,
        targetObjectName: 'messageChannelMessageAssociationMessageFolder',
        targetFieldName: 'messageChannelMessageAssociation',
        settings: {
          relationType: RelationType.ONE_TO_MANY,
        },
      },
      standardObjectMetadataRelatedEntityIds,
      dependencyFlatEntityMaps,
      clientvaultStandardApplicationId,
      now,
    }),
  });
